(start:start {"name":"Chat Start","runtime":{}})
(chatState:current-chat {"name":"Chat State","runtime":{"mode":["input","pending"],"chatId":"{{workflow.input.chatId}}","message":"{{workflow.input.message}}","scopeType":"{{workflow.input.scope.type}}","scopeId":"{{workflow.input.scope.id}}","subjectIds":"{{workflow.input.subjectIds}}","postIds":"{{workflow.input.postIds}}","tagSlugs":"{{workflow.input.tagSlugs}}"}})
(textAnalysis:text-analysis {"name":"Text Analysis","runtime":{"analysisKinds":["confirmation","mutation","workflow-request","workflow-followup","reference-sync","explanation"],"message":"{{current-chat-2.message}}","context":"{{current-chat-2.context}}","pendingPlan":"{{current-chat-2.pendingPlan}}"}})
(agent:ai-agent {"name":"AI Agent","runtime":{"executionMode":"plan-and-run","confirmationPolicy":"mutations-only","modelActionPolicy":"prefer-direct-replies","chatId":"{{workflow.input.chatId}}","message":"{{text-analysis-3.message}}","analysisSummary":"{{text-analysis-3.analysisSummary}}","context":"{{text-analysis-3.context}}","pendingPlan":"{{text-analysis-3.pendingPlan}}","confirmed":"{{text-analysis-3.confirmed}}","mutationIntent":"{{text-analysis-3.mutationIntent}}","workflowRequestIntent":"{{text-analysis-3.workflowRequestIntent}}","workflowFollowupIntent":"{{text-analysis-3.workflowFollowupIntent}}","referenceSyncIntent":"{{text-analysis-3.referenceSyncIntent}}","explanationIntent":"{{text-analysis-3.explanationIntent}}"}})
(model:openai {"name":"AI Model","runtime":{"model":"gpt-4.1-mini","temperature":0,"prompt":"Reply to the user or return strict JSON only when the AI Agent asks for a tool plan."}})
(pendingGate:if-else {"name":"Store Pending Plan?","runtime":{"value":"{{ai-agent-4}}","leftPath":"agent.requires_confirmation","operator":"truthy"}})
(pendingStore:current-chat {"name":"Store Pending Plan","runtime":{"mode":["pending"],"chatId":"{{workflow.input.chatId}}","message":"{{workflow.input.message}}","pendingAction":"store","plan":"{{pendingGate.agent.plan}}"}})
(pendingClear:current-chat {"name":"Clear Pending Plan","runtime":{"mode":["pending"],"chatId":"{{workflow.input.chatId}}","message":"{{workflow.input.message}}","pendingAction":"clear"}})
(finalMerge:merge {"name":"Merge Final Response","runtime":{"input1Value":"{{input}}"}})
(end:respond-end {"name":"Respond End","runtime":{"response":"{{merge-9}}"}})
(channelTool:run-channel-action {"name":"Channel","runtime":{"message":"{{workflow.input.message}}","chatId":"{{workflow.input.chatId}}"}})
(categoryTool:run-category-action {"name":"Category","runtime":{"message":"{{workflow.input.message}}","chatId":"{{workflow.input.chatId}}"}})
(subjectTool:run-subject-action {"name":"Subject","runtime":{"message":"{{workflow.input.message}}","chatId":"{{workflow.input.chatId}}","subjectIds":"{{workflow.input.subjectIds}}"}})
(postTool:run-post-action {"name":"Post","runtime":{"message":"{{workflow.input.message}}","chatId":"{{workflow.input.chatId}}","postIds":"{{workflow.input.postIds}}"}})
(treeTool:run-user-tree-action {"name":"User Tree","runtime":{"message":"{{workflow.input.message}}","chatId":"{{workflow.input.chatId}}"}})
(workflowTool:workflow {"name":"Workflow","runtime":{"operation":"save","workflowIdSource":"input"}})
(executeWorkflowTool:execute-workflow {"name":"Execute Workflow","runtime":{"executionSource":"input-workflow-id"}})
(chatTool:run-chat-action {"name":"Chat","runtime":{"message":"{{workflow.input.message}}","chatId":"{{workflow.input.chatId}}"}})
(chartTool:chart {"name":"Chart","runtime":{"prompt":"{{workflow.input.message}}","libraryId":"auto","chartTemplateId":"auto","outputMode":"both","layoutHeight":360,"colSpan":"12"}})
(channelRouter:action-router {"name":"Channel Actions","runtime":{"toolName":"Channel Actions","toolDescription":"Read and mutate channel records.","broadcastModelId":"run-channel-action","strictConnectionCheck":true}})
(categoryRouter:action-router {"name":"Category Actions","runtime":{"toolName":"Category Actions","toolDescription":"Read and mutate category records.","broadcastModelId":"run-category-action","strictConnectionCheck":true}})
(subjectRouter:action-router {"name":"Subject Actions","runtime":{"toolName":"Subject Actions","toolDescription":"Read and mutate subject records.","broadcastModelId":"run-subject-action","strictConnectionCheck":true}})
(postRouter:action-router {"name":"Post Actions","runtime":{"toolName":"Post Actions","toolDescription":"Read and mutate post records.","broadcastModelId":"run-post-action","strictConnectionCheck":true}})
(treeRouter:action-router {"name":"User Tree Actions","runtime":{"toolName":"User Tree Actions","toolDescription":"Inspect the current user tree.","broadcastModelId":"run-user-tree-action","strictConnectionCheck":true}})
(chatRouter:action-router {"name":"Chat Actions","runtime":{"toolName":"Chat Actions","toolDescription":"Run chat knowledge retrieval actions.","broadcastModelId":"run-chat-action","strictConnectionCheck":true}})
(start)-[:CONNECT {"source":"out:output","target":"in:input"}]->(chatState)
(chatState)-[:CONNECT {"source":"out:output","target":"in:input"}]->(textAnalysis)
(model)-[:CONNECT {"source":"cmd:command","target":"cmd:llm"}]->(agent)
(model)-[:CONNECT {"source":"cmd:command","target":"cmd:llm"}]->(workflowTool)
(model)-[:CONNECT {"source":"cmd:command","target":"cmd:llm"}]->(chartTool)
(textAnalysis)-[:CONNECT {"source":"out:output","target":"in:input"}]->(agent)
(channelRouter)-[:CONNECT {"source":"cmd:command","target":"cmd:tools"}]->(agent)
(categoryRouter)-[:CONNECT {"source":"cmd:command","target":"cmd:tools"}]->(agent)
(subjectRouter)-[:CONNECT {"source":"cmd:command","target":"cmd:tools"}]->(agent)
(postRouter)-[:CONNECT {"source":"cmd:command","target":"cmd:tools"}]->(agent)
(treeRouter)-[:CONNECT {"source":"cmd:command","target":"cmd:tools"}]->(agent)
(chatRouter)-[:CONNECT {"source":"cmd:command","target":"cmd:tools"}]->(agent)
(chartTool)-[:CONNECT {"source":"cmd:command","target":"cmd:tools"}]->(agent)
(workflowTool)-[:CONNECT {"source":"cmd:command","target":"cmd:workflow"}]->(agent)
(executeWorkflowTool)-[:CONNECT {"source":"cmd:command","target":"cmd:workflow"}]->(agent)
(channelTool)-[:CONNECT {"source":"cmd:command","target":"cmd:actions"}]->(channelRouter)
(categoryTool)-[:CONNECT {"source":"cmd:command","target":"cmd:actions"}]->(categoryRouter)
(subjectTool)-[:CONNECT {"source":"cmd:command","target":"cmd:actions"}]->(subjectRouter)
(postTool)-[:CONNECT {"source":"cmd:command","target":"cmd:actions"}]->(postRouter)
(treeTool)-[:CONNECT {"source":"cmd:command","target":"cmd:actions"}]->(treeRouter)
(chatTool)-[:CONNECT {"source":"cmd:command","target":"cmd:actions"}]->(chatRouter)
(agent)-[:CONNECT {"source":"out:output","target":"in:input"}]->(pendingGate)
(agent)-[:CONNECT {"source":"out:output","target":"in:input1"}]->(finalMerge)
(pendingGate)-[:CONNECT {"source":"out:true","target":"in:input"}]->(pendingStore)
(pendingGate)-[:CONNECT {"source":"out:false","target":"in:input"}]->(pendingClear)
(pendingStore)-[:CONNECT {"source":"out:output","target":"in:input2"}]->(finalMerge)
(pendingClear)-[:CONNECT {"source":"out:output","target":"in:input3"}]->(finalMerge)
(finalMerge)-[:CONNECT {"source":"out:output","target":"in:input"}]->(end)
